### ISSUE TITLE
Add a Demo Showing How to Use Dagger Hilt with Crepo

### ISSUE THREAD

**Issue by CoderBDK** [lazy-pr0grammer/Crepo#1]
It would be helpful to have a demo showing how to use Dagger Hilt with Crepo (the repository generator for Retrofit). A simple example demonstrating:

- How to inject the Crepo-generated repository into an Activity, Fragment, or ViewModel using Dagger Hilt.

This would make it easier to understand how to integrate both libraries in an Android project.

**Comment by lazy-pr0grammer** [comment]
@CoderBDK well you can use `@RepoInject` to use hilt with Crepo and currently you need to build the project first to create the repository files then you can do anything with it as you want.
https://github.com/lazy-pr0grammer/Crepo?tab=readme-ov-file#optional-using-repoinject
